/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_CorsRuleGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "CorsRule",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	CorsRuleScope = "VirtualAPI"

	CorsRuleResource = "corsrules"
)

func CorsRuleGVK() apiv1.GroupVersionKind {
	return _CorsRuleGVK
}

func init() {
	apiv1.RegisterGVK(_CorsRuleGVK, CorsRuleScope, CorsRuleResource)
}

// CorsRule Resource
type CorsRule struct {
	apiv1.ResourceMeta

	Owner struct{} `json:"owner"`

	Spec CorsRuleSpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a CorsRule
func (res *CorsRule) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &CorsRuleSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = CorsRule{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

// AsInstance converts a CorsRule to a ResourceInstance
func (res *CorsRule) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	meta := res.ResourceMeta
	meta.GroupVersionKind = CorsRuleGVK()

	return &apiv1.ResourceInstance{ResourceMeta: meta, Spec: spec}, nil
}
