/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_DeploymentGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "Deployment",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	DeploymentScope = "Environment"

	DeploymentResource = "deployments"
)

func DeploymentGVK() apiv1.GroupVersionKind {
	return _DeploymentGVK
}

func init() {
	apiv1.RegisterGVK(_DeploymentGVK, DeploymentScope, DeploymentResource)
}

// Deployment Resource
type Deployment struct {
	apiv1.ResourceMeta

	Owner struct{} `json:"owner"`

	Spec DeploymentSpec `json:"spec"`

	State DeploymentState `json:"state"`
}

// FromInstance converts a ResourceInstance to a Deployment
func (res *Deployment) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &DeploymentSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = Deployment{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

// AsInstance converts a Deployment to a ResourceInstance
func (res *Deployment) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	meta := res.ResourceMeta
	meta.GroupVersionKind = DeploymentGVK()

	return &apiv1.ResourceInstance{ResourceMeta: meta, Spec: spec}, nil
}
