/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_VirtualAPIReleaseGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "VirtualAPIRelease",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	VirtualAPIReleaseScope = ""

	VirtualAPIReleaseResource = "virtualapireleases"
)

func VirtualAPIReleaseGVK() apiv1.GroupVersionKind {
	return _VirtualAPIReleaseGVK
}

func init() {
	apiv1.RegisterGVK(_VirtualAPIReleaseGVK, VirtualAPIReleaseScope, VirtualAPIReleaseResource)
}

// VirtualAPIRelease Resource
type VirtualAPIRelease struct {
	apiv1.ResourceMeta

	Icon struct{} `json:"icon"`

	Owner struct{} `json:"owner"`

	Spec VirtualApiReleaseSpec `json:"spec"`

	State struct{} `json:"state"`
}

// FromInstance converts a ResourceInstance to a VirtualAPIRelease
func (res *VirtualAPIRelease) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &VirtualApiReleaseSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = VirtualAPIRelease{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

// AsInstance converts a VirtualAPIRelease to a ResourceInstance
func (res *VirtualAPIRelease) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	meta := res.ResourceMeta
	meta.GroupVersionKind = VirtualAPIReleaseGVK()

	return &apiv1.ResourceInstance{ResourceMeta: meta, Spec: spec}, nil
}
