/*
 * This file is automatically generated
 */

package v1alpha1

import (
	"encoding/json"

	apiv1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/models/api/v1"
)

var (
	_VirtualServiceGVK = apiv1.GroupVersionKind{
		GroupKind: apiv1.GroupKind{
			Group: "management",
			Kind:  "VirtualService",
		},
		APIVersion: "v1alpha1",
	}
)

const (
	VirtualServiceScope = "VirtualAPI"

	VirtualServiceResource = "virtualservices"
)

func VirtualServiceGVK() apiv1.GroupVersionKind {
	return _VirtualServiceGVK
}

func init() {
	apiv1.RegisterGVK(_VirtualServiceGVK, VirtualServiceScope, VirtualServiceResource)
}

// VirtualService Resource
type VirtualService struct {
	apiv1.ResourceMeta

	Owner struct{} `json:"owner"`

	Spec VirtualServiceSpec `json:"spec"`
}

// FromInstance converts a ResourceInstance to a VirtualService
func (res *VirtualService) FromInstance(ri *apiv1.ResourceInstance) error {
	if ri == nil {
		res = nil
		return nil
	}

	m, err := json.Marshal(ri.Spec)
	if err != nil {
		return err
	}

	spec := &VirtualServiceSpec{}
	err = json.Unmarshal(m, spec)
	if err != nil {
		return err
	}

	*res = VirtualService{ResourceMeta: ri.ResourceMeta, Spec: *spec}

	return err
}

// AsInstance converts a VirtualService to a ResourceInstance
func (res *VirtualService) AsInstance() (*apiv1.ResourceInstance, error) {
	m, err := json.Marshal(res.Spec)
	if err != nil {
		return nil, err
	}

	spec := map[string]interface{}{}
	err = json.Unmarshal(m, &spec)
	if err != nil {
		return nil, err
	}

	meta := res.ResourceMeta
	meta.GroupVersionKind = VirtualServiceGVK()

	return &apiv1.ResourceInstance{ResourceMeta: meta, Spec: spec}, nil
}
