/*
 * This file is automatically generated
 */

package v1alpha1

import (
	v1 "github.com/Axway/agent-sdk/pkg/apic/apiserver/clients/api/v1"
	"github.com/Axway/agent-sdk/pkg/apic/apiserver/models/management/v1alpha1"
)

// GovernanceAgentClient -
type GovernanceAgentClient struct {
	client v1.Scoped
}

// UnscopedGovernanceAgentClient -
type UnscopedGovernanceAgentClient struct {
	client v1.Unscoped
}

// NewGovernanceAgentClient -
func NewGovernanceAgentClient(c v1.Base) (*UnscopedGovernanceAgentClient, error) {

	client, err := c.ForKind(v1alpha1.GovernanceAgentGVK())
	if err != nil {
		return nil, err
	}

	return &UnscopedGovernanceAgentClient{client}, nil

}

// WithScope -
func (c *UnscopedGovernanceAgentClient) WithScope(scope string) *GovernanceAgentClient {
	return &GovernanceAgentClient{
		c.client.WithScope(scope),
	}
}

// List -
func (c *GovernanceAgentClient) List(options ...v1.ListOptions) ([]*v1alpha1.GovernanceAgent, error) {
	riList, err := c.client.List(options...)
	if err != nil {
		return nil, err
	}

	result := make([]*v1alpha1.GovernanceAgent, len(riList))

	for i := range riList {
		result[i] = &v1alpha1.GovernanceAgent{}
		err := result[i].FromInstance(riList[i])
		if err != nil {
			return nil, err
		}
	}

	return result, nil
}

// Get -
func (c *GovernanceAgentClient) Get(name string) (*v1alpha1.GovernanceAgent, error) {
	ri, err := c.client.Get(name)
	if err != nil {
		return nil, err
	}

	service := &v1alpha1.GovernanceAgent{}
	service.FromInstance(ri)

	return service, nil
}

// Delete -
func (c *GovernanceAgentClient) Delete(res *v1alpha1.GovernanceAgent) error {
	ri, err := res.AsInstance()

	if err != nil {
		return err
	}

	return c.client.Delete(ri)
}

// Create -
func (c *GovernanceAgentClient) Create(res *v1alpha1.GovernanceAgent) (*v1alpha1.GovernanceAgent, error) {
	ri, err := res.AsInstance()

	if err != nil {
		return nil, err
	}

	cri, err := c.client.Create(ri)
	if err != nil {
		return nil, err
	}

	created := &v1alpha1.GovernanceAgent{}

	err = created.FromInstance(cri)
	if err != nil {
		return nil, err
	}

	return created, err
}

// Update -
func (c *GovernanceAgentClient) Update(res *v1alpha1.GovernanceAgent) (*v1alpha1.GovernanceAgent, error) {
	ri, err := res.AsInstance()
	if err != nil {
		return nil, err
	}
	resource, err := c.client.Update(ri)
	if err != nil {
		return nil, err
	}

	updated := &v1alpha1.GovernanceAgent{}

	// Updates the resource in place
	err = updated.FromInstance(resource)
	if err != nil {
		return nil, err
	}

	return updated, nil
}
